version: '3.5'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   front:
     depends_on:
       - db
     image: wordpress:4.9.8
     volumes:
       - ./front:/var/www/html
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

#   adminer:
#     image: adminer:latest
#     user: root
#     depends_on:
#       - db
#     restart: always
#     ports:
#       - "8082:8080"
#     environment:
#       ADMINER_DEFAULT_SERVER: db

   back: 
     image: tiangolo/nginx-rtmp
     depends_on:
       - front
     volumes:
       - ./conf/nginx.conf:/etc/nginx/nginx.conf
       - ./channel:/channel
     expose:
       - "8070"
     ports:
       - "8070:8070"
     restart: always
     
   channel:
     depends_on:
       - back
     image: jrottenberg/ffmpeg
     restart: always
     volumes:
       - ./channel:/channel
       - ./conf:/conf
     entrypoint: bash
     command: "/conf/channel.sh"